name: unity-test

on:
  push:
    branches:
      - develop
    tags:
      - "!*"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-unity:
    strategy:
      fail-fast: false
      matrix:
        unity:
          [
            "2018.3.14f1",
            "2018.4.25f1",
            "2019.1.14f1",
            "2019.2.11f1",
            "2019.3.15f1",
            "2019.4.8f1",
            "2020.1.0f1",
            "2020.1.1f1",
            "2020.1.2f1",
          ]

    runs-on: ubuntu-latest
    container:
      # Use Unity image from https://hub.docker.com/r/gableroux/unity3d/tags
      image: gableroux/unity3d:${{ matrix.unity }}

    steps:

      # Activate Unity Editor
      - name: Activate Unity Editor
        id: activation
        run: |
          # Clone ulfs.
          apt update && apt install git -y
          git clone --depth 1 ${{ secrets.ULF_REPO }} .ulfs

          # Activate with ulf.
          ULF_FILE=.ulfs/Unity_v${{ matrix.unity }}.ulf
          echo $ULF_FILE
          if [ -e ${ULF_FILE} ]; then
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile ${ULF_FILE} \
              | grep -E 'LICENSE SYSTEM.*\w{32} != \w{32}' && FAILED=true
          else
            echo "::error:: ulf file '${ULF_FILE}' is not found."
            FAILED=true
          fi

          # Activation failed.
          if [ $FAILED ]; then
            echo "::set-env name=UNITY_VERSION::`echo ${{ matrix.unity }} | cut -d '-' -f 1`"
            echo "::error:: the unity activation may have failed. manual activation is required.%0A \
              1. download the artifact's .alf file.%0A \
              2. Go to https://license.unity3d.com/manual to activate manually.%0A \
              3. Generate a .ulf file from the .alf file and download it.%0A \
              4. Rename .ulf to 'Unity_v${{ matrix.unity }}.ulf'.%0A \
              5. Add file to ulfs repository.%0A \
              5. Re-run the jobs."

            /opt/Unity/Editor/Unity -quit -batchmode -nographics -logFile -createManualActivationFile
            exit 1
          fi

          # Set working directory.
          WORKING_DIR="${{ secrets.WORKING_DIR }}"
          echo "::set-env name=WORKING_DIR::${WORKING_DIR:-.}"

      # (On failed activation) Upload unity activation file
      - name: Upload unity activation file
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Unity_v${{ matrix.unity }}.alf
          path: ./*.alf

      # Checkout
      - uses: actions/checkout@v2

      # Test 1: Build and execute method
      - name: "Test 1: Build and execute method"
        if: always() && steps.activation.conclusion == 'success'
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          rm -rf success_* Packages/.com* Library
          /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod Coffee.Ugd.Runtime.Execute

          [ -e success_compile ] || ( echo "::error:: Compile Script Error" && exit 1 )
          [ -e success_execute ] || ( echo "::error:: Execute Method Error" && exit 1 )

      # Test 2: Run after remove auto-installed packages
      - name: "Test 2: Run after remove auto-installed packages"
        if: always() && steps.activation.conclusion == 'success'
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          rm -rf success_* Packages/.com*
          /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod Coffee.Ugd.Runtime.Execute

          [ -e success_compile ] || ( echo "::error:: Compile Script Error" && exit 1 )
          [ -e success_execute ] || ( echo "::error:: Execute Method Error" && exit 1 )

      # Test 3: Run after remove Library/ScriptAssemblies
      - name: "Test 3: Run after remove Library/ScriptAssemblies"
        if: always() && steps.activation.conclusion == 'success'
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          rm -rf success_* Library/ScriptAssemblies
          /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod Coffee.Ugd.Runtime.Execute

          [ -e success_compile ] || ( echo "::error:: Compile Script Error" && exit 1 )
          [ -e success_execute ] || ( echo "::error:: Execute Method Error" && exit 1 )

      # Test 4: Run after remove Library
      - name: "Test 4: Run after remove Library"
        if: always() && steps.activation.conclusion == 'success'
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          rm -rf success_* Library
          /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod Coffee.Ugd.Runtime.Execute

          [ -e success_compile ] || ( echo "::error:: Compile Script Error" && exit 1 )
          [ -e success_execute ] || ( echo "::error:: Execute Method Error" && exit 1 )
